# Generated by Django 2.2.1 on 2019-06-29 23:13

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190630_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='diary_date',
            field=models.DateField(null=True, validators=[blog.models.no_future]),
        ),
    ]
